--- #---------------- CA orderer Deployment ---------------
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ca-orderer
  name: ca-orderer
  namespace: hyperledger
spec:
  selector:
    matchLabels:
      app: ca-orderer
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ca-orderer
    spec:
      containers:
        - args:
          - sh
          - -c
          - fabric-ca-server start -b admin:adminpw -d
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name: FABRIC_CA_SERVER_CA_NAME
              value: ca-orderer
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "true"
            - name: FABRIC_CA_SERVER_PORT
              value: "9054"
          image: hyperledger/fabric-ca:latest
          name: ca-orderer
          ports:
            - containerPort: 9054
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric-ca-server
              name: ca-orderer-claim0
              readOnly: false
      restartPolicy: Always
      volumes:
        - name: ca-orderer-claim0
          hostPath:            
            path: /host/test-network/organizations/fabric-ca/ordererOrg

---

apiVersion: v1
kind: Service
metadata:
  name: ca-orderer-service
  namespace: hyperledger
spec:
  type: NodePort
  selector:
    app: ca-orderer
  ports:
    - protocol: TCP
      port: 30003
      nodePort: 30003
      targetPort: 9054
