--- #---------------- CA org1 Deployment ---------------
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: peer0-org1-example-com
  name: peer0-org1-example-com
  namespace: hyperledger
spec:
  selector:
    matchLabels:
      app: peer0-org1-example-com
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: peer0-org1-example-com
    spec:
      containers:
        - args:
          - sh
          - -c
          - peer node start
          env:
            - name: FABRIC_LOGGING_SPEC
              value: "INFO"
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_PROFILE_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /etc/hyperledger/fabric/tls/server.crt                
            - name: CORE_PEER_TLS_KEY_FILE
              value: /etc/hyperledger/fabric/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /etc/hyperledger/fabric/tls/ca.crt
            # Peer specific variabes
            - name: CORE_PEER_ID
              value: peer0-org1-example-com
            - name: CORE_PEER_ADDRESS
              value: peer0-org1-example-com:7051            
            - name: CORE_PEER_ADDRESSAUTODETECT
              value: "true"
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: peer0-org1-example-com:7051
            - name: CORE_PEER_GOSSIP_ENDPOINT
              value: peer0-org1-example-com:7051            
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: peer0-org2-example-com:9051
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: localhost:7052
            - name: CORE_PEER_LOCALMSPID
              value: Org1MSP            
            - name: CORE_VM_ENDPOINT
              value: http://localhost:2375
            - name: CORE_OPERATIONS_LISTENADDRESS
              value: 0.0.0.0:9443
          image: hyperledger/fabric-peer:2.3
          name: peer0-org1-example-com
          ports:
            - containerPort: 7051
            - containerPort: 7052
          volumeMounts:        
            - mountPath: /etc/hyperledger/fabric/msp
              name: peer0-org1-example-com-claim0
            - mountPath: /etc/hyperledger/fabric/tls
              name: peer0-org1-example-com-claim1
            - mountPath: /var/hyperledger/production
              name: peer0-org1-example-com-claim2        
            - mountPath: /opt/gopath/src/github.com/hyperledger/fabric-samples        
              name: peer0-org1-example-com-claim3
            - mountPath: /etc/hyperledger/fabric/core.yaml
              name: peer0-org1-example-com-claim4
            # CC Builders
            # - mountPath: /etc/hyperledger/fabric/core.yaml
            #   name: builders-config
            #   subPath: core.yaml
            - mountPath: /builders/external/bin/detect
              name: external-builder-detect
              subPath: detect
            - mountPath: /builders/external/bin/build
              name: external-builder-build
              subPath: build
            - mountPath: /builders/external/bin/release
              name: external-builder-release
              subPath: release
      restartPolicy: Always
      volumes:
        - name: peer0-org1-example-com-claim0
          hostPath:            
            path: /host/test-network/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp
            type: DirectoryOrCreate
        - name: peer0-org1-example-com-claim1
          hostPath:            
            path: /host/test-network/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls
            type: DirectoryOrCreate
        - name: peer0-org1-example-com-claim2
          hostPath:            
            path: peer0.org1.example.com
            type: DirectoryOrCreate
        - name: peer0-org1-example-com-claim3
          hostPath:            
            path: /host
            type: DirectoryOrCreate
        - name: peer0-org1-example-com-claim4
          hostPath:            
            path: /host/config/core.yaml
        # - name: builders-config
        #   configMap:
        #     name: builders-config
        #     items:
        #       - key: core.yaml
        #         path: core.yaml
        - name: external-builder-detect
          configMap:
            name: builders-config
            items:
              - key: detect
                path: detect
                mode: 0777
        - name: external-builder-build
          configMap:
            name: builders-config
            items:
              - key: build
                path: build
                mode: 0777
        - name: external-builder-release
          configMap:
            name: builders-config
            items:
              - key: release
                path: release
                mode: 0777
---

apiVersion: v1
kind: Service
metadata:
  name: peer0-org1-example-com-service
  namespace: hyperledger
spec:
  type: NodePort
  selector:
    app: peer0-org1-example-com
  ports:
    - protocol: TCP
      port: 30005
      nodePort: 30005
      targetPort: 7051