apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-asset-basic-org1
  namespace: hyperledger
  labels:
    app: chaincode-asset-basic-org1
spec:
  selector:
    matchLabels:
      app: chaincode-asset-basic-org1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-asset-basic-org1
    spec:
      containers:
        - image: chaincode/basic:1.0
          name: chaincode-asset-basic-org1
          imagePullPolicy: IfNotPresent
          env:
            - name: CHAINCODE_ID
              value: "basic:a0d72a3fbd49a6f041036fdba4a1fd2186375890a14f64d793efecbbbf6f1b2b"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052

---
  
apiVersion: v1
kind: Service
metadata:
  name: chaincode-asset-basic-org1
  namespace: hyperledger
  labels:
    app: chaincode-asset-basic-org1
spec:
  ports:
    - name: grpc
      port: 7052
      targetPort: 7052
  selector:
    app: chaincode-asset-basic-org1