apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-asset-basic-org2
  namespace: hyperledger
  labels:
    app: chaincode-asset-basic-org2
spec:
  selector:
    matchLabels:
      app: chaincode-asset-basic-org2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-asset-basic-org2
    spec:
      containers:
        - image: chaincode/basic:1.0
          name: chaincode-asset-basic-org2
          imagePullPolicy: IfNotPresent
          env:
            - name: CHAINCODE_ID
              value: "basic:99dba9716eb9c7bea9ee1d7bd444b430f6741bf2f32d790093d356eb608136ff"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:9052"
          ports:
            - containerPort: 9052

---

apiVersion: v1
kind: Service
metadata:
  name: chaincode-asset-basic-org2
  namespace: hyperledger
  labels:
    app: chaincode-asset-basic-org2
spec:
  ports:
    - name: grpc
      port: 9052
      targetPort: 9052
  selector:
    app: chaincode-asset-basic-org2